### ISSUE TITLE
Not boots 

### ISSUE THREAD

**Issue by androidlover5842** [RaphaelFrajuca/android_device_kyleve-logan2g#1]
It's can't boot with incorrect  ramdisk  you need to fix that

**Comment by RaphaelFrajuca** [comment]
ok thanks after i fix ramdisk u.u

**Comment by Grace5921** [comment]
:)

**Comment by RaphaelFrajuca** [comment]
ramdisk fixed

**Comment by RaphaelFrajuca** [comment]
you will test the tree?

**Comment by androidlover5842** [comment]
no i don't have cm-12.1 source or this device . any ways
update this
https://github.com/RaphaelFrajuca/android_device_kyleve-logan2g/blob/cm12.1/device_kyleve.mk#L13
like this
https://github.com/Grace5921/android_device_kyleve/blob/cm-11.0/device_kyleve.mk#L16

**Comment by RaphaelFrajuca** [comment]
ok thanks

**Comment by RaphaelFrajuca** [comment]
this tree is for kyleve

**Comment by RaphaelFrajuca** [comment]
compile and test in kyleve please

**Comment by androidlover5842** [comment]
i don't have source

**Comment by RaphaelFrajuca** [comment]
oh ok ;)
